from pathlib import Path
from datetime import datetime,timezone
from urllib.parse import urlparse
from pypdf import PdfReader
import pandas as pd,json,hashlib
R=Path(__file__).resolve().parents[2];W=Path(__file__).resolve().parent;O=R/'countries/RO/gap_closure_20261001';RAW=R/'data/raw/RO/gap_closure/20261001'
receipts=[json.loads(p.read_text(encoding='utf-8')) for p in sorted(RAW.glob('*/receipt.json'))]
success={x['id']:x for x in receipts if x['status']=='HTTP_OK_UNPARSED'}
success['TSO_ANNUAL_2025']=json.loads((W/'reused_storage_source.json').read_text(encoding='utf-8'))
agency=lambda url:'OPCOM' if 'opcom.ro' in url else 'ANRE' if 'anre.ro' in url else 'Transelectrica' if 'transelectrica.ro' in url else 'BNR' if 'bnr.ro' in url else 'ENTSO-E/Transparency Platform' if 'entsoe' in url or 'transparencyplatform.zendesk.com' in url else 'Portal Legislativ/ANRE' if 'legislatie.just.ro' in url else 'UNKNOWN'
pd.DataFrame([{k:x.get(k) for k in ['id','attempt','dataset','url','method','body','status','retrieved_utc','publication_time','revision_time','raw_file','sha256','bytes','content_type','detected_format','error']}|{'agency':agency(x['url'])} for x in receipts]).to_csv(O/'source_receipt_directory.csv',index=False,encoding='utf-8-sig')
facts=[]
def add(eid,sid,title,dt,loc,layer,fact,limit):
    x=success[sid];facts.append(dict(evidence_id=eid,source_id=sid,agency=agency(x['url']),document_title=title,document_or_effective_date=dt,locator=loc,url=x['url'],access_utc=x['retrieved_utc'],raw_file=x['raw_file'],raw_sha256=x['sha256'],layer=layer,finding=fact,limitation=limit))
add('GC01','SETTLEMENT_FULL_CATALOG','Rezultate decontare Piata de Echilibrare','20 months Jan2025-Aug2026; individual printed date in version catalog','native links; each PDF p1; settlement_price_version_catalog.csv','F/I','UNIQUE/DEFICIT/SURPLUS prices lei/MWh; SYSTEM MWh;191 catalog versions downloaded','latest observed selection I, not final/publication/UTC approval')
add('GC02','STS_MONTH_AUG2025','Raport de Monitorizare Servicii de sistem Luna august2025','report period2025-08; publication date unverified','PDF p4 observations;p5 statistics;p8-12 price tables','F','pay-as-bid since September2024; FCR competitive daily auctions since June2025; capacity lei/hMW; public price arithmetic vs capacity-weighted monthly tables','not unit mapping for every API field; no provider invoice')
add('GC03','STS_DOC_1','Procedura operationala Achizitia capacitatii de echilibrare TEL04.05 Ed1Rev2','filename2024; signed approval/effective date unverified','RAR member PO CAPACITATE ECHILIBRARE 2024 ED1 REV2.pdf p11§8.5.3;p12§8.7.5','F/U','§8.5.3 prints lei/MWh; winning offers contracted at their bid price','literal unit conflict with monthly capacity lei/hMW; no unilateral typo correction')
add('GC04','STS_DOC_2','Procedura operationala Achizitia capacitatii de RSF Rev1','filename09-10-2024; effective date unverified','RAR DOCX; read-only converted PDF p9§8.5.3/4;p10§8.6.3;p12§8.12','F','FCR offers MW and lei/hMW; symmetric equal up/down procurement','no double payment inference; limited energy/eligibility still needs project qualification')
add('GC05','STS_DOC_3','Contract furnizare capacitate RSF participant request template','unfilled template; date unverified','Word read-only PDF p4 Art16-19; p14 Annex3 price header','F','capacity actually realized valued at Annex3 prices, monthly billing and penalties; header lei/h*MW','unfilled framework, no actual invoice or filled per-site rate')
add('GC06','IDA_FORM_EN','OPCOM Raport rezultate licitatii IDA','selected dates2025-01-01 to2026-08-31; historical publication absent','HTML tables4/5/6; headers, native rows/footer; audit CSV','F','three native round tables, price EUR/MWh and volume MW; selected-date public POST works','HTTP/form echo and full query range do not prove numeric/market coverage; blanks not zero')
add('GC07','IDCT_FORM_EN','OPCOM Raport rezultate PI tranzactionare continua','selected dates2025-01-01 to2026-08-31; historical publication absent','HTML table1 first2 header rows, then native occurrences','F','PT15/PT60 price EUR/MWh volume MWh; product/type occurrences','no trade_id/time/full delivery identity; source-side occurrence, no dedup or turnover inference')
add('GC08','OPCOM_DAM_FX_HISTORY_PAGE','Piata pentru Ziua Urmatoare: mecanism si curs de schimb','current source page; historical chain not complete','body paragraph cursul de schimb; calendar links2025/2026','F/I','market trading-day FX uses BNR working-day rule; source I interpretation strict fixing before trading day','page retains hourly language despite QH change; not entire historical procedure approval')
add('GC09','BNR2024_BOUNDARY','BNR annual XML reference rates2024','reference dates2024','XML Cube date and Rate currency EUR','F','boundary fixing dates available in official XML','reference fixing not all markets settlement FX or asof publication')
for yr in [2025,2026]:add('GC10'+str(yr),'FX_CALENDAR_'+str(yr),'Calendarul zilelor de livrare pentru care se introduce rata de schimb in avans PZU',str(yr),'PDF p1 title/legend/colored calendar','F','delivery-calendar advance FX insertion for weekends/holidays','colored date meanings need visual reading; extraction text alone not complete holiday validation')
add('GC11','ANRE_MON_Iunie_2026','Raport monitorizare piata de energie electrica luna iunie2026','report month2026-06; official URL /2026/09 not exact publication proof','PDF p14 2025/2026 OPCOM CET volume and arithmetic price table; rendered visual','F/I','18 months Jan2025-Jun2026 volume GWh, arithmetic price lei/MWh; reprocessed OPCOM monthly reports','second institution aggregate control, not independent measurement; July/Aug26 absent in observed catalog')
add('GC12','ANRE_MON_OCT2025','Raport monitorizare piata de energie electrica luna octombrie2025','2025-10; exact publication unverified','PDF p9 notes1-5;p11 price-clock/weighting notes','F','>5MW monitoring scope; commercial includes transit; SEN consumption from TSO; prosumer own-production consumption excluded from monitored customer consumption; CET arithmetic vs weighted prices separate','does not define SCADA clock/net gross/pumping or prove independent system balance')
add('GC13','TSO_ANNUAL2024_BATTERY','Raport Anual2024 Transelectrica modificare AGA','battery snapshot2025-02-01','PDF p105, paragraph storage (printed sectionp99)','F','13 licensed storage facilities137.2MW269MWh on2025-02-01; qualification totals sum up/down, first commercial reserve battery H2-2023','not2024 yearend; licensed vs operating vs qualified not equivalent')
add('GC19','TSO_ANNUAL_2025','Raport Anual2025 Transelectrica','battery snapshot2025-12-05; prior source acquired2026-09-30','PDF p64 storage paragraph and30groups494MW table','F','installed battery snapshot494MW on2025-12-05; original reused without mutation','not2025 yearend; MWh unknown; access time is original receipt, source re-read2026-10-01')
add('GC14','OPCOM_PI_EVENTS','OPCOM Anunturi Stiri PI','individual notice date; selected events in register','notice list:14Mar2025;23Mar2026','F','historical PI border integration/DST notices present','not complete GCT/rollback chronology and not proof IDA only starts March2025')
add('GC15','TSO_SETTLEMENT_NEWS','Transelectrica lista noutati: corectii decontare PRE','2026-01-15,2026-01-08 listed announcement dates','native notice titles and dates','F','Jan2025 VMA correction following OTS data resubmission; Oct2025 correction following PRE contest','does not establish all version publication times or non-revisable final data')
add('GC16','ANRE_LICENSE_ARCHIVE_20230110','Ord12/2015 licensing regulation ANRE-hosted CTCE consolidation','copy as at2023-01-10; actual compilation includes amendments through2022-03-24','PDF p1 disclaimer and version range','F/U','ANRE archive hosts old consolidation explicitly labeled non-official CTCE information copy','lead/reference only; cannot close valid2025 historical law chain')
add('GC17','ENTSO_HELP_TOKEN','Transparency Platform: How to get security token?','updated2026-01-28','HTML steps1-5 account/RESTful access/token','F','token/account path documented; no token obtained or used','old ENTSO_TOKEN_GUIDE PDF-shaped URL actually returns HTML application shell; no PDF claimed; physical/NTC data not acquired')
add('GC18','ENTSO_HELP_ENDPOINT','Transparency Platform: Request Endpoint','updated2023-06-05','HTML Production environment endpoint paragraph','F','official production endpoint https://web-api.tp.entsoe.eu/api HTTPS only','not tested with token or RO parameters; no data acquisition approval')
fees=[]
for sid,kind,dt,rate,order,scope in [
('TARIFF_DOC_24','system','2024-09-01',11.51,'57/2024','candidate start2025; continuity before June25 not fully proved'),('TARIFF_DOC_20','system','2025-06-01',7.04,'21/2025','document-stated effective date'),('TARIFF_DOC_18','system','2025-09-01',12.79,'60/2025','document-stated effective date'),('TARIFF_DOC_14','system','2026-01-01',14.70,'73/2025','catalog filename73_2026 differs body73/2025'),('TARIFF_DOC_22','TG','2025-01-01',3.29,'99/2024','document-stated effective date'),('TARIFF_DOC_23','TL','2025-01-01',33.03,'99/2024','document-stated effective date'),('TARIFF_DOC_16','TG','2026-01-01',3.63,'74/2025','catalog filename74_2026 differs body74/2025'),('TARIFF_DOC_17','TL','2026-01-01',36.45,'74/2025','document-stated effective date'),('OPCOM_FEE_ARCHIVE_31_QUOTED','OPCOM_variable','2024-07-01',.39,'2024 revision2','dated2024 document only; not asserted valid for all2025'),('OPCOM_FEE_ARCHIVE_15_QUOTED','OPCOM_variable','2026 document',.125,'OPCOM board79/12Dec2025','2026 title; January1 effective day not separately assumed')]:
    m=success[sid];fees.append(dict(source_id=sid,fee_kind=kind,effective_or_document_date=dt,value_lei_per_mwh=rate,authority_reference=order,scope=scope,vat='excluded or applicable addition; see document',url=m['url'],access_utc=m['retrieved_utc'],locator='PDFp1' if sid.startswith('TARIFF') else 'PDFp3 variable tariff',raw_sha256=m['sha256'],site_applicability_verified=False,complete_historical_chain_verified=False))
    add('GC_FEE_'+sid,sid,kind+' published tariff '+order,dt,'PDFp1' if sid.startswith('TARIFF') else 'PDFp3 variable tariff','F/U',f'published rate {rate}lei/MWh; {scope}','not actual storage network/transaction invoice, no assumed exemption/zero fee')
pd.DataFrame(fees).to_csv(O/'fee_timeline.csv',index=False,encoding='utf-8-sig')
pd.DataFrame(facts).to_csv(O/'evidence_register.csv',index=False,encoding='utf-8-sig')
lines=['# 本轮官方来源目录与定位','', '逐个获取尝试、URL、POST参数、原件、哈希和取得时刻见source_receipt_directory.csv；结算191文件目录见settlement_price_version_catalog.csv。正式事实定位见evidence_register.csv。未知发布时间/有效日写未知，未从文件名或取得时间反推。','', '|证据ID|机构/文件|日期性质|位置|URL|访问日期|','|---|---|---|---|---|---|']
for f in facts:lines.append(f"|{f['evidence_id']}|{f['agency']}：{f['document_title']}|{f['document_or_effective_date']}|{f['locator']}|[官方入口]({f['url'].replace(' ','%20')})|{f['access_utc'][:10]}|")
lines+=['','## 政府历史版本网页核对','', '2026-10-01通过网页工具读取政府Portal Legislativ：旧许可[2015条例2022-03-24分支](https://legislatie.just.ro/Public/DetaliiDocument/252838)，定位Art6/10；备用条例[2025-03-27分支](https://legislatie.just.ro/Public/DetaliiDocument/295520)和[2025-05-01分支](https://legislatie.just.ro/Public/DetaliiDocument/295528)，定位istoric consolidări。该检查只确认历史版本入口，未完成逐条差异/过渡/适用期间审核。直接下载尝试403保留，不能据此宣称政府资料不存在或必须申请API。','', '旧已审来源和全期原件仅引用，不改写。2025储能494MW/2025-12-05定位旧TSO_ANNUAL_2025提取文中储能段；最终年度日期核对保持未知。']
(O/'source_directory.md').write_text('\n'.join(lines),encoding='utf-8')
storage=[dict(requested_cutoff='2023-12-31',observed_date='',mw=None,mwh=None,source='ANRE December2023/TSO annual searched; no matching complete cutoff found',scope='unknown true yearend',yearend_verified=False),dict(requested_cutoff='2024-12-31',observed_date='2025-02-01',mw=137.2,mwh=269,source='GC13 TSO annual2024 PDFp105',scope='13 licensed facilities; not yearend substitute',yearend_verified=False),dict(requested_cutoff='2025-12-31',observed_date='2025-12-05',mw=494,mwh=None,source='GC19 reused TSO_ANNUAL_2025 PDFp64',scope='dated snapshot; not yearend substitute; MWh unknown',yearend_verified=False)]
pd.DataFrame(storage).to_csv(O/'storage_cutoff_ledger.csv',index=False,encoding='utf-8-sig')
converted=[]
for p in (W/'derived_official_documents').rglob('*.pdf'):
    source=p.with_suffix('.doc') if p.stem.startswith('STS_DOC_') else next((x for x in (W/'derived_official_documents').rglob('*.docx') if x.stem==p.stem),None)
    if source and source.exists():converted.append(dict(source=source.relative_to(R).as_posix(),source_sha256=hashlib.sha256(source.read_bytes()).hexdigest(),derived=p.relative_to(R).as_posix(),derived_sha256=hashlib.sha256(p.read_bytes()).hexdigest(),method='LibreOffice headless read-only DOC/DOCX to PDF; raw original unchanged; PDF pagination is derivative pagination'))
(W/'document_conversion_provenance.json').write_text(json.dumps(converted,ensure_ascii=False,indent=2),encoding='utf-8')
print(json.dumps({'receipts':len(receipts),'success_ids':len(success),'evidence_rows':len(facts),'fee_rows':len(fees),'converted_pdfs':len(converted)}))
