"""Export scientific descriptive figures, no revenue charts."""
from pathlib import Path
import pandas as pd,numpy as np,matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from matplotlib import font_manager
R=Path(__file__).resolve().parents[2];O=R/'countries/RO/full_period_20261001';D=O/'figures';D.mkdir(exist_ok=True)
font_manager.fontManager.addfont('C:/Windows/Fonts/msyh.ttc');plt.rcParams.update({'font.family':'Microsoft YaHei','font.size':10,'axes.unicode_minus':False,'axes.spines.top':False,'axes.spines.right':False,'figure.dpi':120,'savefig.dpi':180})
def read(n):return pd.read_csv(O/n)
def finish(f,name):
    f.tight_layout();f.savefig(D/(name+'.png'),bbox_inches='tight');f.savefig(D/(name+'.svg'),bbox_inches='tight');plt.close(f)
da=read('da_monthly_statistics.csv');x=np.arange(len(da));labels=da.month.str[2:]
f,axs=plt.subplots(2,1,figsize=(12,7),sharex=True)
axs[0].plot(x,da.time_mean_eur_mwh,'o-',label='时间加权均价');axs[0].plot(x,da.volume_weighted_mean_eur_mwh,'s--',label='成交量加权均价');axs[0].fill_between(x,da.p05,da.p95,alpha=.16,label='5%–95%分位数');axs[0].set_ylabel('EUR/MWh');axs[0].legend(ncol=3);axs[0].set_title('日前价格：2025-01至2026-08，58,364个QH描述映射；保留原生合同')
axs[1].bar(x,da.negative_hours,color='#c85b42',label='负价');axs[1].bar(x,da.zero_hours,bottom=da.negative_hours,color='#aeb8c4',label='零价');axs[1].set_ylabel('实际小时');axs[1].set_xticks(x,labels,rotation=45);axs[1].legend();finish(f,'01_da_monthly')
h=read('da_hourly_heatmap_values.csv');grid=h.pivot(index='month',columns='hour',values='mean');f,ax=plt.subplots(figsize=(12,7));im=ax.imshow(grid,aspect='auto',cmap='RdYlBu_r',vmin=grid.min().min(),vmax=grid.max().max());ax.set_yticks(range(len(grid)),grid.index);ax.set_xticks(range(24));ax.set_xlabel('Bucharest当地钟点');ax.set_title('日前月×钟点均价（按实际时长加权，EUR/MWh；色标覆盖全部值）');f.colorbar(im,ax=ax,label='EUR/MWh');finish(f,'02_da_heatmap')
w=read('price_windows_2h_4h_daily.csv');w['month']=w.local_date.str[:7];g=w.groupby(['month','duration_hours']).price_window_range.median().unstack();f,ax=plt.subplots(figsize=(12,4));g.plot(ax=ax,marker='o');ax.set_ylabel('EUR/MWh');ax.set_title('每日连续2h/4h价格窗口极差中位数：每配置608天\n高低窗口先后顺序未约束；不代表储能收益');ax.legend(['2h','4h']);ax.tick_params(axis='x',rotation=45);finish(f,'03_price_windows')
l=read('load_monthly_statistics.csv');curve=read('load_duration_curve.csv');f,axs=plt.subplots(1,2,figsize=(13,4.7));axs[0].plot(x,l.mean_mw,'o-',label='均值');axs[0].plot(x,l.peak_mw,'--',label='峰值');axs[0].plot(x,l.minimum_mw,':',label='谷值');axs[0].set_xticks(x,labels,rotation=70);axs[0].set_ylabel('MW');axs[0].legend();axs[0].set_title('DAMAS实际毛负荷：全部58,364个QH');axs[1].plot(curve.hours_exceeded,curve.gross_load_mw);axs[1].set_xlabel('累计超过小时');axs[1].set_ylabel('MW');axs[1].set_title('毛负荷持续曲线');finish(f,'04_load')
s=read('scada_monthly_statistics.csv');cols=['coal_mw','hydrocarbons_mw','hydro_mw','nuclear_mw','wind_mw','solar_mw','bio_mw','storage_mw'];names=['煤','烃类','水电（未拆抽蓄）','核','风','光','生物质','Stocare原始字段'];mix=s[s.field.isin(cols)].pivot(index='month',columns='field',values='mean_mw').reindex(columns=cols);f,ax=plt.subplots(figsize=(12,5));ax.stackplot(np.arange(len(mix)),*mix.values.T,labels=names);ax.set_xticks(range(len(mix)),mix.index.str[2:],rotation=45);ax.set_ylabel('已观测小时平均MW');ax.set_title('SCADA分技术出力：14,567个原生小时；2026-07缺1日\nprosumer及净/毛边界未完整核定，Stocare未解释为净充放电');ax.legend(ncol=4,loc='upper left',fontsize=8);finish(f,'05_scada_mix')
j=read('scada_price_joint_under_clock_A.csv');bins=np.linspace(j.scada_residual_consumption_minus_wind_solar_mw.min(),j.scada_residual_consumption_minus_wind_solar_mw.max(),20);j['bin']=pd.cut(j.scada_residual_consumption_minus_wind_solar_mw,bins);b=j.groupby('bin',observed=True).agg(residual=('scada_residual_consumption_minus_wind_solar_mw','mean'),price=('da_time_mean_eur_mwh','mean'),count=('da_time_mean_eur_mwh','size'));f,ax=plt.subplots(figsize=(9,5));hb=ax.hexbin(j.scada_residual_consumption_minus_wind_solar_mw,j.da_time_mean_eur_mwh,gridsize=40,mincnt=1,cmap='Blues',bins='log');ax.plot(b.residual,b.price,'o-',color='#c85b42',label='分箱均价');f.colorbar(hb,ax=ax,label='小时样本数（对数）');ax.set_xlabel('SCADA表内 Consum − Eoliana − Foto（MW）');ax.set_ylabel('日前小时均价（EUR/MWh）');ax.set_title('残余需求与日前价：14,496小时，时钟映射为A假设\n排除3个DST日及错日期日；不证明因果或定价机组');ax.legend();finish(f,'06_scada_residual')
c=read('capacity_monthly_statistics.csv');f,axs=plt.subplots(2,1,figsize=(12,7),sharex=True)
for product,g in c.groupby('product',sort=False):
    g=g.set_index('month').reindex(da.month);axs[0].plot(x,g.demand_mean_mw,marker='.',label=product);axs[1].plot(x,g.accepted_price_mean_raw_LEI,marker='.',label=product)
axs[0].set_ylabel('需求MW');axs[0].set_title('容量统计：5产品，69,327个投标区间内小时记录\n无招标记录≠零需求；5个产品日缺1小时');axs[0].legend(ncol=5);axs[1].set_ylabel('LEI原始统计数值\n支付分母未核定');axs[1].set_xticks(x,labels,rotation=45);axs[1].set_title('平均接受价格字段（不计算支付、不换汇）');finish(f,'07_capacity_raw')
a=read('activation_monthly_statistics.csv');f,axs=plt.subplots(2,1,figsize=(12,7),sharex=True)
for product in ['aFRR_Up','aFRR_Down','mFRR_Up','mFRR_Down']:
    g=a[a.product_direction==product].set_index('month').reindex(da.month);axs[0].plot(x,g.observed_energy_mwh/1000,'o-',label=product)
axs[0].set_ylabel('已观测GWh');axs[0].legend(ncol=4);axs[0].set_title('系统激活量：MWh原值求和，未再乘0.25\naFRR上/下各45/46个缺值，图中仅已观测量，不代表完整月总量')
for product in ['aFRR_Up','aFRR_Down']:
    g=a[a.product_direction==product].set_index('month').reindex(da.month);axs[1].plot(x,g.numeric/g.structural*100,'o-',label=product)
axs[1].set_ylim(98,100.1);axs[1].set_ylabel('数值覆盖%');axs[1].set_xticks(x,labels,rotation=45);axs[1].legend();finish(f,'08_activation')
co=read('commercial_exchange_monthly.csv');imports=['huro','mdro','uaro','bgro','rsro'];co['sign']=np.where(co.direction.isin(imports),1,-1);co['signed']=co.observed_scheduled_energy_mwh*co.sign/1e6;g=co.groupby('month').signed.sum();f,ax=plt.subplots(figsize=(12,4));ax.bar(x,g.reindex(da.month),color='#436c96');ax.axhline(0,color='black',lw=.6);ax.set_xticks(x,labels,rotation=45);ax.set_ylabel('计划净进口TWh');ax.set_title('商业交换计划：进口−出口；58,364个QH\n不是物理流或实际系统平衡差额');finish(f,'09_commercial_schedule')
coverage=read('monthly_coverage.csv');select=coverage[(coverage.dataset=='DA')|(coverage.field.isin(['grossRealizedConsumption','aFRR_Up','aFRR_Down']))|((coverage.dataset=='capacity')&coverage.field.str.endswith('demand MW'))].copy();select['label']=select.dataset+' / '+select.field;select['percent']=select.numeric/select.expected*100;grid=select.pivot(index='label',columns='month',values='percent');f,ax=plt.subplots(figsize=(12,5));im=ax.imshow(grid,aspect='auto',vmin=0,vmax=100,cmap='YlGn');ax.set_yticks(range(len(grid)),grid.index);ax.set_xticks(range(len(grid.columns)),grid.columns.str[2:],rotation=45);ax.set_title('每字段数值覆盖（%）：0%表示未取得，不证明市场不存在\n完整覆盖仍不代表语义、历史发布或模型门禁通过');f.colorbar(im,ax=ax,label='数值覆盖%');finish(f,'10_coverage')
annual=pd.read_csv(R/'countries/RO/data_samples_20260930/annual_structure_samples.csv');g=annual[annual.metric.str.endswith('gross installed') & ~annual.metric.str.startswith('Total')].copy();g['year']=g.period_or_asof.str[:4];grid=g.pivot(index='year',columns='metric',values='source_value').astype(float);f,axs=plt.subplots(1,2,figsize=(13,5));grid.plot.bar(stacked=True,ax=axs[0],rot=0);axs[0].set_ylabel('MW');axs[0].set_title('年末许可商业运行发电装机\n2023/2024/2025，试运行机组除外');axs[0].legend(['水','核','可再生','火'],fontsize=8)
dates=['2025-12-05','2026-04-01','2026-07-01','2026-09-01'];power=[494,599,924.43,1161.488];axs[1].plot(dates,power,'o-',label='官方报告安装功率/最新表Pi');axs[1].set_ylabel('MW');axs[1].tick_params(axis='x',rotation=30);axs[1].set_title('储能截面：非同日期年末、非可随时调用容量\nMWh: 2026-04=1129.7、07=1762.5、09=2310.221');axs[1].legend(fontsize=8);finish(f,'11_installed')
events=read('deterministic_event_cards.csv');base=read('joint_descriptive_price_load_exchange.csv').merge(read('activatedBalancingEnergyOverview.csv')[['delivery_start_utc','aFRR_Up','aFRR_Down']],on='delivery_start_utc',validate='one_to_one');base['t']=pd.to_datetime(base.delivery_start_utc,utc=True);contexts=[];f,axs=plt.subplots(len(events),2,figsize=(13,16))
for i,r in events.iterrows():
    start=pd.Timestamp(r.anchor_utc);end=pd.Timestamp(r.end_utc) if pd.notna(r.end_utc) else start+pd.Timedelta(minutes=15);g=base[(base.t>=start-pd.Timedelta(hours=12))&(base.t<end+pd.Timedelta(hours=12))].copy();g['event_kind']=r['kind'];contexts.append(g.drop(columns='t'));hours=(g.t-start).dt.total_seconds()/3600
    ax=axs[i,0];ax.plot(hours,g.price_eur_mwh,color='#436c96');ax.set_ylabel('日前EUR/MWh',color='#436c96');ax2=ax.twinx();ax2.plot(hours,g.grossRealizedConsumption,color='#b67244',alpha=.7);ax2.set_ylabel('毛负荷MW',color='#b67244');ax.set_title(r['kind']+' | '+r.anchor_utc+' | n='+str(len(g)),fontsize=8);ax.axvspan(0,(end-start).total_seconds()/3600,alpha=.1,color='grey')
    ax=axs[i,1];ax.plot(hours,g.aFRR_Up,label='aFRR Up');ax.plot(hours,g.aFRR_Down,label='aFRR Down');ax.set_ylabel('系统MWh/原生QH');ax.set_title('原值；缺值不填；相对事件起点实际小时',fontsize=8);ax.axvspan(0,(end-start).total_seconds()/3600,alpha=.1,color='grey');ax.legend(fontsize=8)
    for ax in axs[i]:ax.set_xlabel('相对UTC事件起点小时')
f.suptitle('统一规则选取5个事件的前后过程：价格、毛负荷和系统激活\n相关过程不证明因果、本站履约或边际技术',y=1.002);finish(f,'12_event_context');pd.concat(contexts).to_csv(O/'event_context_qh.csv',index=False,encoding='utf-8-sig')
print('figures',len(list(D.glob('*.png'))),'PNG+SVG')
